name: Generate changeset

on:
  workflow_dispatch:
  pull_request_target:
    paths:
      - '.github/workflows/renovate.yaml'
      - '**/package.json'
      - '**/package-lock.json'

jobs:
  generate-changeset:
    name: Generate changeset
    runs-on: ubuntu-latest
    timeout-minutes: 15
    if: github.actor == 'renovate[bot]'
    steps:
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.11.0
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          token: ${{secrets.PAT}}
          fetch-depth: 0

      - name: Configure git
        run: |
          git config user.email "bot@mazanec.dev"
          git config user.name "Bot"

      - name: Generate changeset
        uses: actions/github-script@v6
        with:
          script: |
            let { promises: fs } = require('fs');

            async function getPackagesNames(files) {
              let names = [];

              for (let file of files) {
                let data = JSON.parse(await fs.readFile(file, 'utf8'));

                if (!data.private) {
                  names.push(data.name);
                }
              }

              return names;
            }

            async function createChangeset(fileName, packageBumps, packages) {
              let message = '';

              for (let [packageName, bump] of packageBumps) {
                message =
                  message + `Dependency \`${packageName}\` updated to \`${bump}\`.\n`;
              }

              let header = packages
                .map((packageName) => `'${packageName}': patch`)
                .join('\n');

              await fs.writeFile(fileName, `---\n${header}\n---\n${message.trim()}\n`);
            }

            async function getBumps(files) {
              let bumps = new Map();

              for (let file of files) {
                let { stdout: changes } = await exec.getExecOutput('git', ['show', file]);

                for (let change of changes.split('\n')) {
                  if (!change.startsWith('+ ')) {
                    continue;
                  }

                  let match = change.match(/"(.*?)"/g);

                  bumps.set(match[0].replace(/"/g, ''), match[1].replace(/"/g, ''));
                }
              }

              return bumps;
            }

            let branch = await exec.getExecOutput('git branch --show-current');

            if (!branch.stdout.startsWith('renovate/')) {
              console.log('Not a renovate branch, skipping...');

              return;
            }

            let diffOutput = await exec.getExecOutput('git diff --name-only HEAD~1');
            let diffFiles = diffOutput.stdout.split('\n');

            if (diffFiles.find((diffFile) => diffFile.startsWith('.changeset'))) {
              console.log('Changeset already exists, skipping...');

              return;
            }

            let files = diffFiles
              .filter((file) => file !== 'package.json') // skip root package.json
              .filter((file) => file.includes('package.json'));
            let packageNames = await getPackagesNames(files);

            if (!packageNames.length) {
              console.log('No package.json changes to published packages, skipping...');

              return;
            }

            let { stdout: shortHash } = await exec.getExecOutput(
              'git rev-parse --short HEAD',
            );
            let fileName = `.changeset/renovate-${shortHash.trim()}.md`;
            let packageBumps = await getBumps(files);

            await createChangeset(fileName, packageBumps, packageNames);
            await exec.exec('git', ['add', fileName]);
            await exec.exec('git commit -C HEAD --amend --no-edit');
            await exec.exec('git push --force');
