name: Check pull request

on:
  pull_request:
    branches:
      - development

jobs:
  pull_request_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          fetch-depth: 0

      - uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install packages
        run: npm ci

      - name: Run tests
        run: npm run test

      - name: Check for changesets
        run: npx changeset status --since=origin/development
